sonarqube:
  build: "5.1.1"
  ports:
   - "9000:9000"
   - "5432:5432"
  volumes:
   - /opt/sonar/extensions/plugins:/opt/sonarqube/extensions/plugins
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://localhost:5432/sonar

db:
  image: postgres
  net: container:sonarqube
  # Add VOLUMEs to allow backup of config and databases
  # volumes:
  # - /opt/sonar/db/var/lib/postgresql:/var/lib/postgresql
  # - /opt/sonar/db/etc/postgresql:/etc/postgresql
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar